apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "chart.name" . }}